package com.bdmplatform.transaction.smart.script.estimator

import com.bdmplatform.lang.v1.estimator.ScriptEstimatorV1

class ContractScriptComplexityV1Test extends ContractScriptComplexityTest(ScriptEstimatorV1)