package com.bdmplatform.transaction.smart.script.estimator

import com.bdmplatform.lang.v2.estimator.ScriptEstimatorV2

class ContractScriptComplexityV2Test extends ContractScriptComplexityTest(ScriptEstimatorV2)